# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e2c284f5d58e16a08f3209f17ab445d"
name = "profitable-benchmark-app"
handle = "profitable-benchmark-app-4"
application_url = "https://ampland-recycling-mn-toolkit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myy-storee-testt.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ampland-recycling-mn-toolkit.trycloudflare.com/auth/callback",
  "https://ampland-recycling-mn-toolkit.trycloudflare.com/auth/shopify/callback",
  "https://ampland-recycling-mn-toolkit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
